# Generated by Django 3.1 on 2021-01-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210101_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
