# Generated by Django 3.1 on 2021-01-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210101_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('PayPal', 'PayPal'), ('Credit Card', 'Credit Card')], max_length=50, null=True),
        ),
    ]
