# Generated by Django 3.1 on 2021-01-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charge',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
