# Generated by Django 3.1 on 2021-01-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20210101_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='free_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
