# Generated by Django 3.1 on 2021-02-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_coupon_free_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_strie_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
