# Generated by Django 3.1 on 2021-02-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_coupon_coupon_strie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_strie_id',
            new_name='coupon_stripe_id',
        ),
    ]
