# Generated by Django 3.1 on 2021-02-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20210201_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_id',
            new_name='coupon_name',
        ),
    ]
