# Generated by Django 3.1 on 2021-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_remove_coupon_coupon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan_purchased',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
