# Generated by Django 3.1 on 2020-08-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='stam', max_length=200),
            preserve_default=False,
        ),
    ]
