# Generated by Django 3.1 on 2020-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='europeCitizenship',
            field=models.BooleanField(default=False),
        ),
    ]
