# Generated by Django 3.1 on 2020-08-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_europecitizenship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='europeCitizenship',
            field=models.BooleanField(),
        ),
    ]
