# Generated by Django 3.1 on 2020-08-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200831_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='europeCitizenship',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
