# Generated by Django 3.1 on 2020-09-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200831_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
