# Generated by Django 3.1 on 2020-12-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_vat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter_optin',
            field=models.BooleanField(default=True),
        ),
    ]
