# Generated by Django 3.1 on 2021-01-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_newsletter_optin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
