# Generated by Django 3.1 on 2021-01-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
