# Generated by Django 3.1 on 2021-02-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
