# Generated by Django 3.1 on 2021-02-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_max_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan_name',
            field=models.CharField(blank=True, default='free', max_length=100, null=True),
        ),
    ]
