# Generated by Django 3.1 on 2021-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('price_monthly', models.IntegerField(default=0)),
                ('price_monthly_stripe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('price_yearly', models.IntegerField(default=0)),
                ('price_yearly_stripe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('stripe_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
