# Generated by Django 3.1 on 2021-01-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='players',
            field=models.IntegerField(default=0),
        ),
    ]
