# Generated by Django 3.1 on 2021-01-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_plan_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='payment_term',
            field=models.CharField(choices=[('Year', 'Year'), ('Month', 'Month')], default='Month', max_length=10),
        ),
    ]
