# Generated by Django 3.1 on 2021-01-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_plan_payment_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='payment_term',
            field=models.CharField(choices=[('year', 'year'), ('month', 'month')], default='Month', max_length=10),
        ),
    ]
