# Generated by Django 3.1 on 2021-01-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20210131_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='payment_term',
            field=models.CharField(choices=[('year', 'year'), ('month', 'month')], default='month', max_length=10),
        ),
    ]
