# Generated by Django 3.1 on 2021-01-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20210131_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='payment_term',
        ),
    ]
