# Generated by Django 3.1 on 2021-01-09 07:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True)),
                ('button_text', models.CharField(blank=True, max_length=20, null=True)),
                ('button_link', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(choices=[('he', 'he'), ('en', 'en')], default='en', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('title_1', models.CharField(blank=True, max_length=100, null=True)),
                ('content_1', ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True)),
                ('title_2', models.CharField(blank=True, max_length=100, null=True)),
                ('content_2', ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True)),
                ('title_3', models.CharField(blank=True, max_length=100, null=True)),
                ('content_3', ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True)),
                ('language', models.CharField(choices=[('English', 'en'), ('Hebrew', 'he'), ('Spanish', 'es')], default='English', max_length=20)),
                ('button_text', models.CharField(blank=True, max_length=20, null=True)),
                ('button_link', models.CharField(blank=True, max_length=200, null=True)),
                ('recipients_type', models.CharField(blank=True, max_length=20, null=True)),
                ('recipients', models.JSONField(blank=True, default=list, null=True)),
                ('recipients_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
