# Generated by Django 3.1 on 2021-01-10 06:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content_2',
            field=ckeditor.fields.RichTextField(blank=True, max_length=7000, null=True),
        ),
    ]
