# Generated by Django 3.1 on 2021-01-17 14:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20210110_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content_1',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='content_2',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='content_3',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
    ]
