# Generated by Django 3.1 on 2020-11-03 08:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('content', ckeditor.fields.RichTextField(max_length=100000, null=True)),
                ('language', models.CharField(choices=[('Hebrew', 'he'), ('English', 'en')], default='English', max_length=20)),
                ('section', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
