# Generated by Django 3.1 on 2020-11-05 10:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_main', '0002_contentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
