# Generated by Django 3.1 on 2020-11-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_main', '0004_contentpage_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpage',
            old_name='name',
            new_name='page',
        ),
    ]
