# Generated by Django 3.1 on 2020-11-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_main', '0005_auto_20201110_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpage',
            old_name='image',
            new_name='image_id',
        ),
        migrations.AddField(
            model_name='contentpage',
            name='image_1',
            field=models.ImageField(blank=True, default='profile_pics/placeholder.png', null=True, upload_to='content_images'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='image_2',
            field=models.ImageField(blank=True, default='profile_pics/placeholder.png', null=True, upload_to='content_images'),
        ),
    ]
