# Generated by Django 3.1 on 2020-11-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_main', '0006_auto_20201110_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpage',
            old_name='page',
            new_name='name',
        ),
    ]
