# Generated by Django 3.1 on 2020-12-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_main', '0007_auto_20201110_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
