# Generated by Django 3.1 on 2020-12-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_main', '0008_auto_20201217_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
