# Generated by Django 3.1 on 2020-12-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_main', '0010_auto_20201227_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='language',
            field=models.CharField(choices=[('Hebrew', 'he'), ('English', 'en')], default='English', max_length=20),
        ),
    ]
