# Generated by Django 3.1 on 2020-09-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='board',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.board'),
        ),
    ]
