# Generated by Django 3.1 on 2020-08-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10, null=True),
        ),
    ]
