# Generated by Django 3.1 on 2020-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_album_album_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_type',
        ),
        migrations.AddField(
            model_name='album',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
