# Generated by Django 3.1 on 2020-09-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200916_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='board',
        ),
        migrations.AddField(
            model_name='board',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='board_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
