# Generated by Django 3.1 on 2020-09-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_game_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
