# Generated by Django 3.1 on 2020-09-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200916_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='game_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
