# Generated by Django 3.1 on 2020-09-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_player_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='board',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
