# Generated by Django 3.1 on 2020-09-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_board_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='winnings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
