# Generated by Django 3.1 on 2020-09-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200907_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_requested',
            field=models.BooleanField(default=False),
        ),
    ]
