# Generated by Django 3.1 on 2020-11-05 10:08

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_winnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.picture_image_path),
        ),
    ]
