# Generated by Django 3.1 on 2020-11-05 13:18

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_picture_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to=game.models.picture_image_path),
        ),
    ]
