# Generated by Django 3.1 on 2020-09-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_game_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='remote_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
