# Generated by Django 3.1 on 2020-09-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_picture_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='prizes',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
