# Generated by Django 3.1 on 2020-11-05 13:24

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20201105_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.picture_image_path),
        ),
    ]
