# Generated by Django 3.1 on 2020-09-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_prizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='prizes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
