# Generated by Django 3.1 on 2020-08-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200829_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='pictures',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
