# Generated by Django 3.1 on 2020-09-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200913_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winning_conditions',
            field=models.CharField(choices=[('ROWS', 'ROWS'), ('2_ROWS', '2_ROWS'), ('FULL_ONLY', 'FULL_ONLY'), ('ALL', 'ALL')], default='ALL', max_length=10),
        ),
    ]
