# Generated by Django 3.1 on 2020-09-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20200913_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='board',
            name='rows',
        ),
        migrations.AddField(
            model_name='board',
            name='pictures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
