# Generated by Django 3.1 on 2020-08-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20200829_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='board',
        ),
        migrations.AddField(
            model_name='album',
            name='Board',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
