# Generated by Django 3.1 on 2020-11-08 14:42

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20201105_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='auto_join_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_1_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.prize_image_path),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_1_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_2_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.prize_image_path),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_2_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_3_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.prize_image_path),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_3_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
