# Generated by Django 3.1 on 2020-08-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20200829_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Board',
            new_name='board',
        ),
    ]
