# Generated by Django 3.1 on 2020-09-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20200914_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
