# Generated by Django 3.1 on 2020-11-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_picture_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
