# Generated by Django 3.1 on 2020-09-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_game_board_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='album_id',
            new_name='album',
        ),
    ]
