# Generated by Django 3.1 on 2020-09-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20200914_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winning_conditions',
            field=models.JSONField(default=list),
        ),
    ]
