# Generated by Django 3.1 on 2020-11-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20201110_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='not_approved',
            field=models.BooleanField(default=False),
        ),
    ]
