# Generated by Django 3.1 on 2020-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20200915_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pictures_pool',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='shown_pictures',
            field=models.JSONField(default=list),
        ),
    ]
