# Generated by Django 3.1 on 2020-11-11 13:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_player_not_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pictures',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
