# Generated by Django 3.1 on 2020-11-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20201111_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
