# Generated by Django 3.1 on 2020-11-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_picture_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.picture'),
        ),
    ]
