# Generated by Django 3.1 on 2020-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_game_current_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winning_conditions',
            field=models.CharField(blank=True, default='bingo', max_length=10, null=True),
        ),
    ]
