# Generated by Django 3.1 on 2020-09-16 04:44

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20200916_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(blank=True, default=game.models.random_string, max_length=4, null=True),
        ),
    ]
