# Generated by Django 3.1 on 2020-11-13 09:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_board_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pictures_draw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
