# Generated by Django 3.1 on 2020-11-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_board_pictures_draw'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='boad_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
