# Generated by Django 3.1 on 2020-11-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20201116_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_id',
            new_name='board_number',
        ),
    ]
