# Generated by Django 3.1 on 2020-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20201116_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='prizes_won',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
