# Generated by Django 3.1 on 2020-11-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_game_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='prize_2_won',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_3_won',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
