# Generated by Django 3.1 on 2020-11-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_auto_20201117_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='prize_2_locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='prize_3_locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
