# Generated by Django 3.1 on 2020-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20201118_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='public_approved',
            field=models.BooleanField(default=False),
        ),
    ]
