# Generated by Django 3.1 on 2020-12-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_album_public_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
