# Generated by Django 3.1 on 2020-12-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_auto_20201216_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
