# Generated by Django 3.1 on 2020-12-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_auto_20201216_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='public_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
