# Generated by Django 3.1 on 2020-12-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_game_current_winning_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
