# Generated by Django 3.1 on 2020-12-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_game_game_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bingo_shouts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
