# Generated by Django 3.1 on 2021-01-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_displaypicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaypicture',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
