# Generated by Django 3.1 on 2021-01-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_picture_matched'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayPicture',
        ),
    ]
