# Generated by Django 3.1 on 2021-01-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_auto_20210104_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='auto_matching',
            field=models.BooleanField(default=False),
        ),
    ]
