# Generated by Django 3.1 on 2021-01-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0044_game_auto_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
