# Generated by Django 3.1 on 2021-01-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_auto_20210110_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
