# Generated by Django 3.1 on 2021-01-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.CharField(blank=True, choices=[('Movies', 'movies'), ('Music', 'Music'), ('Animals', 'animals'), ('Religion', 'religion'), ('Politics', 'politics'), ('Finance', 'finance'), ('Art', 'art'), ('Games', 'games'), ('Other', 'other')], max_length=100, null=True),
        ),
    ]
