# Generated by Django 3.1 on 2021-01-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_category'),
        ('game', '0048_auto_20210112_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.category'),
        ),
    ]
