# Generated by Django 3.1 on 2021-01-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0049_album_album_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='category',
        ),
    ]
