# Generated by Django 3.1 on 2020-09-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_cost', models.FloatField(blank=True, null=True)),
                ('vat', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
