# Generated by Django 3.1 on 2020-09-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='game_cost',
            new_name='value_float',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='vat',
            new_name='value_integer',
        ),
        migrations.AddField(
            model_name='control',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
